### ISSUE TITLE
Team to test: CS2113T-T12-1:The program fails catastrophically, cannot even launch

### ISSUE THREAD

**Issue by WEIFENG-NUSCEG** [AY1920S1-CS2113T-T12-1/main#119]
Error log in the attached file
<img width="744" alt="Screenshot 2019-11-01 at 4 55 31 PM" src="https://user-images.githubusercontent.com/42437159/68016172-f2e3f900-fcce-11e9-8a72-53e2060a1665.png">

**Comment by CheeSengg** [comment]
The program can be run by double clicking on the jar file. You do not have to run on terminal
