### ISSUE TITLE
UI screenshot AND team members photo doesn't appear in the project page

### ISSUE THREAD

**Issue by okkhoy** [AY1920S1-CS2113T-T12-1/main#142]
Check: https://nuscs2113-ay1920s1.github.io/website/admin/projectList.html#t12-1

Read:
![image](https://user-images.githubusercontent.com/1023494/68544420-faf21600-03fd-11ea-9695-68061df76c31.png)

**Comment by NicholasLiu97** [comment]
Closed with commit 83a2eca
