### ISSUE TITLE
Update JavaDocs

### ISSUE THREAD

**Issue by CheeSengg** [AY1920S1-CS2113T-T12-1/main#57]
update JavaDocs for the following packages:
-commands
-util
-core

Each of us to handle one of it.

**Comment by CheeSengg** [comment]
Updated JavaDocs:
-Optix.java
-Ui.java
-OptixDateFormatter.java
-Parser.java
-ShowMap.java
-OptixInvalidCommandException.java
-OptixInvalidDateException.java
-ByeCommand.java
-HelpCommand.java
-Command.java

**Comment by NicholasLiu97** [comment]
All javadocs updated
